# image will be published to ghcr.io/<user>/<name>
name: zumnebelos
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
      - https://negativo17.org/repos/fedora-nvidia.repo
      - https://negativo17.org/repos/fedora-multimedia.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-rawhide/varlad-zellij.repo
      
    install:
      - fish
      - micro
      - starship
      # sudo rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra --install kernel-cachyos
      #- kernel-cachyos
      #- kernel-cacyos-devel-matched
      - libcap-ng-devel
      - procps-ng-devel
      #- uksmd-rawhide
      - zellij
    
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      #- kernel
      #- kernel-core
      #- kernel-modules
      #- kernel-modules-core
      #- kernel-modules-extra

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - com.github.tchx84.Flatseal
      - com.valvesoftware.Steam
      - com.valvesoftware.SteamLink
      - org.freedesktop.Platform.VulkanLayer.gamescope
      - com.heroicgameslauncher.hgl
      - re.sonny.Junction
      - com.obsproject.Studio
      - com.obsproject.Studio.Plugin.BackgroundRemoval
      - com.obsproject.Studio.Plugin.DroidCam
      - com.obsproject.Studio.Plugin.GStreamerVaapi
      - com.obsproject.Studio.Plugin.Gstreamer
      - com.obsproject.Studio.Plugin.InputOverlay
      - com.obsproject.Studio.Plugin.MoveTransition
      - com.obsproject.Studio.Plugin.OBSLivesplitOne
      - com.obsproject.Studio.Plugin.OBSVkCapture
      - com.obsproject.Studio.Plugin.RewardsTheater
      - com.obsproject.Studio.Plugin.ScaleToSound
      - com.obsproject.Studio.Plugin.SceneSwitcher
      - com.obsproject.Studio.Plugin.TransitionTable
      - org.mozilla.Thunderbird
      - org.mozilla.firefox
      - org.localsend.localsend_app
      - io.github.mrvladus.List
      - io.podman_desktop.PodmanDesktop
      - com.usebottles.bottles
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
